version: "3.7"
services:
  app:
    image: node:14-alpine
    ports:
      - 80:80
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: dicoding
      MYSQL_DB: todo-db
      volumes:
  todo-mysql-data: